# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.common_file import CommonFile

class TestCommonFile(unittest.TestCase):
    """CommonFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonFile:
        """Test CommonFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonFile`
        """
        model = CommonFile()
        if include_optional:
            return CommonFile(
                s_file_name = 'example.pdf',
                s_file_url = '',
                s_file_base64 = '[B@63c5efee',
                e_file_source = 'Base64'
            )
        else:
            return CommonFile(
                s_file_name = 'example.pdf',
                e_file_source = 'Base64',
        )
        """

    def testCommonFile(self):
        """Test CommonFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
