"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.13
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.field_pki_ezmaxinvoicing_id import FieldPkiEzmaxinvoicingID
from eZmaxApi.model.field_yyyymm_ezmaxinvoicing import FieldYyyymmEzmaxinvoicing
globals()['FieldPkiEzmaxinvoicingID'] = FieldPkiEzmaxinvoicingID
globals()['FieldYyyymmEzmaxinvoicing'] = FieldYyyymmEzmaxinvoicing
from eZmaxApi.model.ezmaxinvoicing_autocomplete_element_response import EzmaxinvoicingAutocompleteElementResponse


class TestEzmaxinvoicingAutocompleteElementResponse(unittest.TestCase):
    """EzmaxinvoicingAutocompleteElementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzmaxinvoicingAutocompleteElementResponse(self):
        """Test EzmaxinvoicingAutocompleteElementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzmaxinvoicingAutocompleteElementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
