"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.15
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.common_audit import CommonAudit
from eZmaxApi.model.ezsignbulksend_response import EzsignbulksendResponse
from eZmaxApi.model.ezsignbulksend_response_compound_all_of import EzsignbulksendResponseCompoundAllOf
from eZmaxApi.model.ezsignbulksenddocumentmapping_response_compound import EzsignbulksenddocumentmappingResponseCompound
from eZmaxApi.model.ezsignbulksendsignermapping_response import EzsignbulksendsignermappingResponse
from eZmaxApi.model.field_e_ezsignfoldertype_privacylevel import FieldEEzsignfoldertypePrivacylevel
from eZmaxApi.model.field_pki_ezsignbulksend_id import FieldPkiEzsignbulksendID
from eZmaxApi.model.field_pki_ezsignfoldertype_id import FieldPkiEzsignfoldertypeID
from eZmaxApi.model.field_pki_language_id import FieldPkiLanguageID
globals()['CommonAudit'] = CommonAudit
globals()['EzsignbulksendResponse'] = EzsignbulksendResponse
globals()['EzsignbulksendResponseCompoundAllOf'] = EzsignbulksendResponseCompoundAllOf
globals()['EzsignbulksenddocumentmappingResponseCompound'] = EzsignbulksenddocumentmappingResponseCompound
globals()['EzsignbulksendsignermappingResponse'] = EzsignbulksendsignermappingResponse
globals()['FieldEEzsignfoldertypePrivacylevel'] = FieldEEzsignfoldertypePrivacylevel
globals()['FieldPkiEzsignbulksendID'] = FieldPkiEzsignbulksendID
globals()['FieldPkiEzsignfoldertypeID'] = FieldPkiEzsignfoldertypeID
globals()['FieldPkiLanguageID'] = FieldPkiLanguageID
from eZmaxApi.model.ezsignbulksend_response_compound import EzsignbulksendResponseCompound


class TestEzsignbulksendResponseCompound(unittest.TestCase):
    """EzsignbulksendResponseCompound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsignbulksendResponseCompound(self):
        """Test EzsignbulksendResponseCompound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsignbulksendResponseCompound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
