# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.header_accept_language import HeaderAcceptLanguage

class TestHeaderAcceptLanguage(unittest.TestCase):
    """HeaderAcceptLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeaderAcceptLanguage(self):
        """Test HeaderAcceptLanguage"""
        # inst = HeaderAcceptLanguage()

if __name__ == '__main__':
    unittest.main()
