"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.10
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.field_pki_ezsignformfield_id import FieldPkiEzsignformfieldID


class TestFieldPkiEzsignformfieldID(unittest.TestCase):
    """FieldPkiEzsignformfieldID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldPkiEzsignformfieldID(self):
        """Test FieldPkiEzsignformfieldID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldPkiEzsignformfieldID()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
