# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.domain_get_object_v2_response_m_payload import DomainGetObjectV2ResponseMPayload

class TestDomainGetObjectV2ResponseMPayload(unittest.TestCase):
    """DomainGetObjectV2ResponseMPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainGetObjectV2ResponseMPayload:
        """Test DomainGetObjectV2ResponseMPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DomainGetObjectV2ResponseMPayload`
        """
        model = DomainGetObjectV2ResponseMPayload()
        if include_optional:
            return DomainGetObjectV2ResponseMPayload(
                obj_domain = eZmaxApi.models.domain_response_compound.domain-ResponseCompound()
            )
        else:
            return DomainGetObjectV2ResponseMPayload(
                obj_domain = eZmaxApi.models.domain_response_compound.domain-ResponseCompound(),
        )
        """

    def testDomainGetObjectV2ResponseMPayload(self):
        """Test DomainGetObjectV2ResponseMPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
