# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.ezsignbulksendsignermapping_response import EzsignbulksendsignermappingResponse

class TestEzsignbulksendsignermappingResponse(unittest.TestCase):
    """EzsignbulksendsignermappingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EzsignbulksendsignermappingResponse:
        """Test EzsignbulksendsignermappingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EzsignbulksendsignermappingResponse`
        """
        model = EzsignbulksendsignermappingResponse()
        if include_optional:
            return EzsignbulksendsignermappingResponse(
                pki_ezsignbulksendsignermapping_id = 57,
                fki_ezsignbulksend_id = 8,
                fki_user_id = 70,
                s_ezsignbulksendsignermapping_description = 'Supervisor'
            )
        else:
            return EzsignbulksendsignermappingResponse(
                pki_ezsignbulksendsignermapping_id = 57,
                fki_ezsignbulksend_id = 8,
                s_ezsignbulksendsignermapping_description = 'Supervisor',
        )
        """

    def testEzsignbulksendsignermappingResponse(self):
        """Test EzsignbulksendsignermappingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
