"""
    eZmax API Definition

    This API expose all the functionnalities for the eZmax and eZsign application.  # noqa: E501

    The version of the OpenAPI document: 1.0.30
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import unittest

import eZmaxinc/eZmax-SDK-python
from eZmaxinc/eZmax-SDK-python.api.object_apikey_api import ObjectApikeyApi  # noqa: E501


class TestObjectApikeyApi(unittest.TestCase):
    """ObjectApikeyApi unit test stubs"""

    def setUp(self):
        self.api = ObjectApikeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apikey_create_object_v1(self):
        """Test case for apikey_create_object_v1

        Create a new Apikey  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
