# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.signature_get_object_v2_response import SignatureGetObjectV2Response

class TestSignatureGetObjectV2Response(unittest.TestCase):
    """SignatureGetObjectV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignatureGetObjectV2Response:
        """Test SignatureGetObjectV2Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignatureGetObjectV2Response`
        """
        model = SignatureGetObjectV2Response()
        if include_optional:
            return SignatureGetObjectV2Response(
                m_payload = eZmaxApi.models.signature_get_object_v2_response_m_payload.signature-getObject-v2-Response-mPayload(
                    obj_signature = eZmaxApi.models.signature_response_compound.signature-ResponseCompound(), )
            )
        else:
            return SignatureGetObjectV2Response(
                m_payload = eZmaxApi.models.signature_get_object_v2_response_m_payload.signature-getObject-v2-Response-mPayload(
                    obj_signature = eZmaxApi.models.signature_response_compound.signature-ResponseCompound(), ),
        )
        """

    def testSignatureGetObjectV2Response(self):
        """Test SignatureGetObjectV2Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
