# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.user_edit_colleagues_v2_request import UserEditColleaguesV2Request

class TestUserEditColleaguesV2Request(unittest.TestCase):
    """UserEditColleaguesV2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserEditColleaguesV2Request:
        """Test UserEditColleaguesV2Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserEditColleaguesV2Request`
        """
        model = UserEditColleaguesV2Request()
        if include_optional:
            return UserEditColleaguesV2Request(
                a_obj_colleague = [
                    eZmaxApi.models.colleague_request_compound_v2.colleague-RequestCompoundV2()
                    ]
            )
        else:
            return UserEditColleaguesV2Request(
                a_obj_colleague = [
                    eZmaxApi.models.colleague_request_compound_v2.colleague-RequestCompoundV2()
                    ],
        )
        """

    def testUserEditColleaguesV2Request(self):
        """Test UserEditColleaguesV2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
