# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eZmaxApi.models.emailstatic_response_compound import EmailstaticResponseCompound  # noqa: E501

class TestEmailstaticResponseCompound(unittest.TestCase):
    """EmailstaticResponseCompound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailstaticResponseCompound:
        """Test EmailstaticResponseCompound
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailstaticResponseCompound`
        """
        model = EmailstaticResponseCompound()  # noqa: E501
        if include_optional:
            return EmailstaticResponseCompound(
                pki_emailstatic_id = 99,
                s_emailstatic_address = 'email@example.com'
            )
        else:
            return EmailstaticResponseCompound(
                pki_emailstatic_id = 99,
                s_emailstatic_address = 'email@example.com',
        )
        """

    def testEmailstaticResponseCompound(self):
        """Test EmailstaticResponseCompound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
