"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.14
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.field_e_ezsignsignature_type import FieldEEzsignsignatureType


class TestFieldEEzsignsignatureType(unittest.TestCase):
    """FieldEEzsignsignatureType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldEEzsignsignatureType(self):
        """Test FieldEEzsignsignatureType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldEEzsignsignatureType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
