"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.12
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.common_response import CommonResponse
from eZmaxApi.model.common_response_obj_debug import CommonResponseObjDebug
from eZmaxApi.model.common_response_obj_debug_payload import CommonResponseObjDebugPayload
from eZmaxApi.model.ezmaxinvoicing_get_provisional_v1_response_all_of import EzmaxinvoicingGetProvisionalV1ResponseAllOf
from eZmaxApi.model.ezmaxinvoicing_get_provisional_v1_response_m_payload import EzmaxinvoicingGetProvisionalV1ResponseMPayload
globals()['CommonResponse'] = CommonResponse
globals()['CommonResponseObjDebug'] = CommonResponseObjDebug
globals()['CommonResponseObjDebugPayload'] = CommonResponseObjDebugPayload
globals()['EzmaxinvoicingGetProvisionalV1ResponseAllOf'] = EzmaxinvoicingGetProvisionalV1ResponseAllOf
globals()['EzmaxinvoicingGetProvisionalV1ResponseMPayload'] = EzmaxinvoicingGetProvisionalV1ResponseMPayload
from eZmaxApi.model.ezmaxinvoicing_get_provisional_v1_response import EzmaxinvoicingGetProvisionalV1Response


class TestEzmaxinvoicingGetProvisionalV1Response(unittest.TestCase):
    """EzmaxinvoicingGetProvisionalV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzmaxinvoicingGetProvisionalV1Response(self):
        """Test EzmaxinvoicingGetProvisionalV1Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzmaxinvoicingGetProvisionalV1Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
