# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.api.object_usergroupmembership_api import ObjectUsergroupmembershipApi


class TestObjectUsergroupmembershipApi(unittest.TestCase):
    """ObjectUsergroupmembershipApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectUsergroupmembershipApi()

    def tearDown(self) -> None:
        pass

    def test_usergroupmembership_create_object_v1(self) -> None:
        """Test case for usergroupmembership_create_object_v1

        Create a new Usergroupmembership
        """
        pass

    def test_usergroupmembership_delete_object_v1(self) -> None:
        """Test case for usergroupmembership_delete_object_v1

        Delete an existing Usergroupmembership
        """
        pass

    def test_usergroupmembership_edit_object_v1(self) -> None:
        """Test case for usergroupmembership_edit_object_v1

        Edit an existing Usergroupmembership
        """
        pass

    def test_usergroupmembership_get_object_v2(self) -> None:
        """Test case for usergroupmembership_get_object_v2

        Retrieve an existing Usergroupmembership
        """
        pass


if __name__ == '__main__':
    unittest.main()
