# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.usergroupexternal_response import UsergroupexternalResponse

class TestUsergroupexternalResponse(unittest.TestCase):
    """UsergroupexternalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsergroupexternalResponse:
        """Test UsergroupexternalResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsergroupexternalResponse`
        """
        model = UsergroupexternalResponse()
        if include_optional:
            return UsergroupexternalResponse(
                pki_usergroupexternal_id = 16,
                s_usergroupexternal_name = 'Administrators',
                s_usergroupexternal_id = '5140-1542'
            )
        else:
            return UsergroupexternalResponse(
                pki_usergroupexternal_id = 16,
                s_usergroupexternal_name = 'Administrators',
                s_usergroupexternal_id = '5140-1542',
        )
        """

    def testUsergroupexternalResponse(self):
        """Test UsergroupexternalResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
