# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.scim_group import ScimGroup

class TestScimGroup(unittest.TestCase):
    """ScimGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScimGroup:
        """Test ScimGroup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScimGroup`
        """
        model = ScimGroup()
        if include_optional:
            return ScimGroup(
                id = '',
                display_name = 'Administration',
                members = [
                    eZmaxApi.models.scim_group_member.Scim-GroupMember(
                        value = '', 
                        display = '', 
                        type = '', 
                        __ref = '', )
                    ]
            )
        else:
            return ScimGroup(
                display_name = 'Administration',
        )
        """

    def testScimGroup(self):
        """Test ScimGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
