"""
    eZmax API Definition

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.0.31
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import unittest

import eZmaxinc/eZmax-SDK-python
from eZmaxinc/eZmax-SDK-python.api.module_sspr_api import ModuleSsprApi  # noqa: E501


class TestModuleSsprApi(unittest.TestCase):
    """ModuleSsprApi unit test stubs"""

    def setUp(self):
        self.api = ModuleSsprApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sspr_remind_usernames_v1(self):
        """Test case for sspr_remind_usernames_v1

        Remind of forgotten username(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
