"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.13
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.ezsigntemplatesignature_response_compound import EzsigntemplatesignatureResponseCompound
globals()['EzsigntemplatesignatureResponseCompound'] = EzsigntemplatesignatureResponseCompound
from eZmaxApi.model.ezsigntemplatesignature_get_object_v2_response_m_payload import EzsigntemplatesignatureGetObjectV2ResponseMPayload


class TestEzsigntemplatesignatureGetObjectV2ResponseMPayload(unittest.TestCase):
    """EzsigntemplatesignatureGetObjectV2ResponseMPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsigntemplatesignatureGetObjectV2ResponseMPayload(self):
        """Test EzsigntemplatesignatureGetObjectV2ResponseMPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsigntemplatesignatureGetObjectV2ResponseMPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
