# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.multilingual_billingentityinternal_description import MultilingualBillingentityinternalDescription

class TestMultilingualBillingentityinternalDescription(unittest.TestCase):
    """MultilingualBillingentityinternalDescription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultilingualBillingentityinternalDescription:
        """Test MultilingualBillingentityinternalDescription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultilingualBillingentityinternalDescription`
        """
        model = MultilingualBillingentityinternalDescription()
        if include_optional:
            return MultilingualBillingentityinternalDescription(
                s_billingentityinternal_description1 = 'Défaut',
                s_billingentityinternal_description2 = 'Default'
            )
        else:
            return MultilingualBillingentityinternalDescription(
        )
        """

    def testMultilingualBillingentityinternalDescription(self):
        """Test MultilingualBillingentityinternalDescription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
