"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.7
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.ezsigntemplatesignature_response import EzsigntemplatesignatureResponse
from eZmaxApi.model.ezsigntemplatesignature_response_compound_all_of import EzsigntemplatesignatureResponseCompoundAllOf
from eZmaxApi.model.ezsigntemplatesignaturecustomdate_response_compound import EzsigntemplatesignaturecustomdateResponseCompound
from eZmaxApi.model.field_e_ezsigntemplatesignature_font import FieldEEzsigntemplatesignatureFont
from eZmaxApi.model.field_e_ezsigntemplatesignature_tooltipposition import FieldEEzsigntemplatesignatureTooltipposition
from eZmaxApi.model.field_e_ezsigntemplatesignature_type import FieldEEzsigntemplatesignatureType
globals()['EzsigntemplatesignatureResponse'] = EzsigntemplatesignatureResponse
globals()['EzsigntemplatesignatureResponseCompoundAllOf'] = EzsigntemplatesignatureResponseCompoundAllOf
globals()['EzsigntemplatesignaturecustomdateResponseCompound'] = EzsigntemplatesignaturecustomdateResponseCompound
globals()['FieldEEzsigntemplatesignatureFont'] = FieldEEzsigntemplatesignatureFont
globals()['FieldEEzsigntemplatesignatureTooltipposition'] = FieldEEzsigntemplatesignatureTooltipposition
globals()['FieldEEzsigntemplatesignatureType'] = FieldEEzsigntemplatesignatureType
from eZmaxApi.model.ezsigntemplatesignature_response_compound import EzsigntemplatesignatureResponseCompound


class TestEzsigntemplatesignatureResponseCompound(unittest.TestCase):
    """EzsigntemplatesignatureResponseCompound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsigntemplatesignatureResponseCompound(self):
        """Test EzsigntemplatesignatureResponseCompound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsigntemplatesignatureResponseCompound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
