"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.10
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.ezsigntemplatedocument_edit_ezsigntemplatesignatures_v1_response_m_payload import EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload
globals()['EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload'] = EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseMPayload
from eZmaxApi.model.ezsigntemplatedocument_edit_ezsigntemplatesignatures_v1_response_all_of import EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf


class TestEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf(unittest.TestCase):
    """EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf(self):
        """Test EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsigntemplatedocumentEditEzsigntemplatesignaturesV1ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
