# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.user_get_permissions_v1_response import UserGetPermissionsV1Response

class TestUserGetPermissionsV1Response(unittest.TestCase):
    """UserGetPermissionsV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserGetPermissionsV1Response:
        """Test UserGetPermissionsV1Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserGetPermissionsV1Response`
        """
        model = UserGetPermissionsV1Response()
        if include_optional:
            return UserGetPermissionsV1Response(
                m_payload = eZmaxApi.models.user_get_permissions_v1_response_m_payload.user-getPermissions-v1-Response-mPayload(
                    a_obj_modulegroup = [
                        eZmaxApi.models.modulegroup_response_compound.modulegroup-ResponseCompound()
                        ], )
            )
        else:
            return UserGetPermissionsV1Response(
                m_payload = eZmaxApi.models.user_get_permissions_v1_response_m_payload.user-getPermissions-v1-Response-mPayload(
                    a_obj_modulegroup = [
                        eZmaxApi.models.modulegroup_response_compound.modulegroup-ResponseCompound()
                        ], ),
        )
        """

    def testUserGetPermissionsV1Response(self):
        """Test UserGetPermissionsV1Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
