"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.16
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.common_response import CommonResponse
from eZmaxApi.model.common_response_obj_debug import CommonResponseObjDebug
from eZmaxApi.model.common_response_obj_debug_payload import CommonResponseObjDebugPayload
from eZmaxApi.model.ezsignfolder_get_ezsignfoldersignerassociations_v1_response_all_of import EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
from eZmaxApi.model.ezsignfolder_get_ezsignfoldersignerassociations_v1_response_m_payload import EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload
globals()['CommonResponse'] = CommonResponse
globals()['CommonResponseObjDebug'] = CommonResponseObjDebug
globals()['CommonResponseObjDebugPayload'] = CommonResponseObjDebugPayload
globals()['EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf'] = EzsignfolderGetEzsignfoldersignerassociationsV1ResponseAllOf
globals()['EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload'] = EzsignfolderGetEzsignfoldersignerassociationsV1ResponseMPayload
from eZmaxApi.model.ezsignfolder_get_ezsignfoldersignerassociations_v1_response import EzsignfolderGetEzsignfoldersignerassociationsV1Response


class TestEzsignfolderGetEzsignfoldersignerassociationsV1Response(unittest.TestCase):
    """EzsignfolderGetEzsignfoldersignerassociationsV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsignfolderGetEzsignfoldersignerassociationsV1Response(self):
        """Test EzsignfolderGetEzsignfoldersignerassociationsV1Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsignfolderGetEzsignfoldersignerassociationsV1Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
