"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.14
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.field_pki_ezsignfolder_id import FieldPkiEzsignfolderID
globals()['FieldPkiEzsignfolderID'] = FieldPkiEzsignfolderID
from eZmaxApi.model.custom_ezmaxinvoicing_ezsignfolder_response_all_of import CustomEzmaxinvoicingEzsignfolderResponseAllOf


class TestCustomEzmaxinvoicingEzsignfolderResponseAllOf(unittest.TestCase):
    """CustomEzmaxinvoicingEzsignfolderResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomEzmaxinvoicingEzsignfolderResponseAllOf(self):
        """Test CustomEzmaxinvoicingEzsignfolderResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomEzmaxinvoicingEzsignfolderResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
