# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.field_e_user_origin import FieldEUserOrigin

class TestFieldEUserOrigin(unittest.TestCase):
    """FieldEUserOrigin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldEUserOrigin(self):
        """Test FieldEUserOrigin"""
        # inst = FieldEUserOrigin()

if __name__ == '__main__':
    unittest.main()
