"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.15
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.branding_create_object_v1_response_all_of import BrandingCreateObjectV1ResponseAllOf
from eZmaxApi.model.branding_create_object_v1_response_m_payload import BrandingCreateObjectV1ResponseMPayload
from eZmaxApi.model.common_response import CommonResponse
from eZmaxApi.model.common_response_obj_debug import CommonResponseObjDebug
from eZmaxApi.model.common_response_obj_debug_payload import CommonResponseObjDebugPayload
globals()['BrandingCreateObjectV1ResponseAllOf'] = BrandingCreateObjectV1ResponseAllOf
globals()['BrandingCreateObjectV1ResponseMPayload'] = BrandingCreateObjectV1ResponseMPayload
globals()['CommonResponse'] = CommonResponse
globals()['CommonResponseObjDebug'] = CommonResponseObjDebug
globals()['CommonResponseObjDebugPayload'] = CommonResponseObjDebugPayload
from eZmaxApi.model.branding_create_object_v1_response import BrandingCreateObjectV1Response


class TestBrandingCreateObjectV1Response(unittest.TestCase):
    """BrandingCreateObjectV1Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrandingCreateObjectV1Response(self):
        """Test BrandingCreateObjectV1Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BrandingCreateObjectV1Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
