"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.10
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.ezsigntemplatedocument_request_patch import EzsigntemplatedocumentRequestPatch


class TestEzsigntemplatedocumentRequestPatch(unittest.TestCase):
    """EzsigntemplatedocumentRequestPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEzsigntemplatedocumentRequestPatch(self):
        """Test EzsigntemplatedocumentRequestPatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EzsigntemplatedocumentRequestPatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
