# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.ezdoctemplatedocument_request import EzdoctemplatedocumentRequest

class TestEzdoctemplatedocumentRequest(unittest.TestCase):
    """EzdoctemplatedocumentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EzdoctemplatedocumentRequest:
        """Test EzdoctemplatedocumentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EzdoctemplatedocumentRequest`
        """
        model = EzdoctemplatedocumentRequest()
        if include_optional:
            return EzdoctemplatedocumentRequest(
                pki_ezdoctemplatedocument_id = 95,
                fki_language_id = 2,
                fki_ezsignfoldertype_id = 5,
                fki_ezdoctemplatetype_id = 7,
                fki_ezdoctemplatefieldtypecategory_id = 4,
                e_ezdoctemplatedocument_privacylevel = 'Company',
                b_ezdoctemplatedocument_isactive = True,
                obj_ezdoctemplatedocument_name = eZmaxApi.models.multilingual_ezdoctemplatedocument_name.Multilingual-EzdoctemplatedocumentName(
                    s_ezdoctemplatedocument_name1 = 'Contrat type', 
                    s_ezdoctemplatedocument_name2 = 'Standard Contract', )
            )
        else:
            return EzdoctemplatedocumentRequest(
                fki_language_id = 2,
                fki_ezdoctemplatetype_id = 7,
                fki_ezdoctemplatefieldtypecategory_id = 4,
                b_ezdoctemplatedocument_isactive = True,
                obj_ezdoctemplatedocument_name = eZmaxApi.models.multilingual_ezdoctemplatedocument_name.Multilingual-EzdoctemplatedocumentName(
                    s_ezdoctemplatedocument_name1 = 'Contrat type', 
                    s_ezdoctemplatedocument_name2 = 'Standard Contract', ),
        )
        """

    def testEzdoctemplatedocumentRequest(self):
        """Test EzdoctemplatedocumentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
