# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.models.field_e_webhook_ezsignevent import FieldEWebhookEzsignevent

class TestFieldEWebhookEzsignevent(unittest.TestCase):
    """FieldEWebhookEzsignevent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldEWebhookEzsignevent(self):
        """Test FieldEWebhookEzsignevent"""
        # inst = FieldEWebhookEzsignevent()

if __name__ == '__main__':
    unittest.main()
