# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eZmaxApi.api.object_ezsignsignergroupmembership_api import ObjectEzsignsignergroupmembershipApi  # noqa: E501


class TestObjectEzsignsignergroupmembershipApi(unittest.TestCase):
    """ObjectEzsignsignergroupmembershipApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectEzsignsignergroupmembershipApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_ezsignsignergroupmembership_create_object_v1(self) -> None:
        """Test case for ezsignsignergroupmembership_create_object_v1

        Create a new Ezsignsignergroupmembership  # noqa: E501
        """
        pass

    def test_ezsignsignergroupmembership_delete_object_v1(self) -> None:
        """Test case for ezsignsignergroupmembership_delete_object_v1

        Delete an existing Ezsignsignergroupmembership  # noqa: E501
        """
        pass

    def test_ezsignsignergroupmembership_get_object_v2(self) -> None:
        """Test case for ezsignsignergroupmembership_get_object_v2

        Retrieve an existing Ezsignsignergroupmembership  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
