"""
    eZmax API Definition

    This API expose all the functionnalities for the eZmax and eZsign applications.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Contact: support-api@ezmax.ca
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eZmaxApi
from eZmaxApi.model.custom_autocomplete_element_response import CustomAutocompleteElementResponse


class TestCustomAutocompleteElementResponse(unittest.TestCase):
    """CustomAutocompleteElementResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomAutocompleteElementResponse(self):
        """Test CustomAutocompleteElementResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomAutocompleteElementResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
