# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eZmaxApi.models.field_e_systemconfiguration_language1 import FieldESystemconfigurationLanguage1

class TestFieldESystemconfigurationLanguage1(unittest.TestCase):
    """FieldESystemconfigurationLanguage1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldESystemconfigurationLanguage1(self):
        """Test FieldESystemconfigurationLanguage1"""
        # inst = FieldESystemconfigurationLanguage1()

if __name__ == '__main__':
    unittest.main()
