# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eZmaxApi.models.field_e_ezsignfolder_step import FieldEEzsignfolderStep

class TestFieldEEzsignfolderStep(unittest.TestCase):
    """FieldEEzsignfolderStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldEEzsignfolderStep(self):
        """Test FieldEEzsignfolderStep"""
        # inst = FieldEEzsignfolderStep()

if __name__ == '__main__':
    unittest.main()
