# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from eZmaxApi.models.ezsigntsarequirement_get_autocomplete_v2_response_m_payload import EzsigntsarequirementGetAutocompleteV2ResponseMPayload  # noqa: E501

class TestEzsigntsarequirementGetAutocompleteV2ResponseMPayload(unittest.TestCase):
    """EzsigntsarequirementGetAutocompleteV2ResponseMPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EzsigntsarequirementGetAutocompleteV2ResponseMPayload:
        """Test EzsigntsarequirementGetAutocompleteV2ResponseMPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EzsigntsarequirementGetAutocompleteV2ResponseMPayload`
        """
        model = EzsigntsarequirementGetAutocompleteV2ResponseMPayload()  # noqa: E501
        if include_optional:
            return EzsigntsarequirementGetAutocompleteV2ResponseMPayload(
                a_obj_ezsigntsarequirement = [
                    eZmaxApi.models.ezsigntsarequirement_autocomplete_element_response.ezsigntsarequirement-AutocompleteElement-Response(
                        s_ezsigntsarequirement_description_x = 'Default', 
                        pki_ezsigntsarequirement_id = 1, 
                        b_ezsigntsarequirement_isactive = True, 
                        b_disabled = True, )
                    ]
            )
        else:
            return EzsigntsarequirementGetAutocompleteV2ResponseMPayload(
                a_obj_ezsigntsarequirement = [
                    eZmaxApi.models.ezsigntsarequirement_autocomplete_element_response.ezsigntsarequirement-AutocompleteElement-Response(
                        s_ezsigntsarequirement_description_x = 'Default', 
                        pki_ezsigntsarequirement_id = 1, 
                        b_ezsigntsarequirement_isactive = True, 
                        b_disabled = True, )
                    ],
        )
        """

    def testEzsigntsarequirementGetAutocompleteV2ResponseMPayload(self):
        """Test EzsigntsarequirementGetAutocompleteV2ResponseMPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
