# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from eZmaxApi.models.common_report import CommonReport
from eZmaxApi.models.common_reportcellstyle import CommonReportcellstyle

class CommonReportgroup(BaseModel):
    """
    A group of reports  Each Reportgroup is for a specific recipient or for a specific context.  # noqa: E501
    """
    a_obj_report: conlist(CommonReport) = Field(..., alias="a_objReport")
    a_obj_reportcellstyle_custom: conlist(CommonReportcellstyle) = Field(..., alias="a_objReportcellstyleCustom")
    __properties = ["a_objReport", "a_objReportcellstyleCustom"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CommonReportgroup:
        """Create an instance of CommonReportgroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in a_obj_report (list)
        _items = []
        if self.a_obj_report:
            for _item in self.a_obj_report:
                if _item:
                    _items.append(_item.to_dict())
            _dict['a_objReport'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in a_obj_reportcellstyle_custom (list)
        _items = []
        if self.a_obj_reportcellstyle_custom:
            for _item in self.a_obj_reportcellstyle_custom:
                if _item:
                    _items.append(_item.to_dict())
            _dict['a_objReportcellstyleCustom'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CommonReportgroup:
        """Create an instance of CommonReportgroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CommonReportgroup.parse_obj(obj)

        _obj = CommonReportgroup.parse_obj({
            "a_obj_report": [CommonReport.from_dict(_item) for _item in obj.get("a_objReport")] if obj.get("a_objReport") is not None else None,
            "a_obj_reportcellstyle_custom": [CommonReportcellstyle.from_dict(_item) for _item in obj.get("a_objReportcellstyleCustom")] if obj.get("a_objReportcellstyleCustom") is not None else None
        })
        return _obj


