# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class CommonResponseObjSQLQuery(BaseModel):
    """
    Definition of objSQLQuery Object  # noqa: E501
    """
    s_query: StrictStr = Field(..., alias="sQuery", description="The SQL Query")
    f_duration: Union[StrictFloat, StrictInt] = Field(..., alias="fDuration", description="Execution time of the SQL Query in seconds")
    __properties = ["sQuery", "fDuration"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CommonResponseObjSQLQuery:
        """Create an instance of CommonResponseObjSQLQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CommonResponseObjSQLQuery:
        """Create an instance of CommonResponseObjSQLQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CommonResponseObjSQLQuery.parse_obj(obj)

        _obj = CommonResponseObjSQLQuery.parse_obj({
            "s_query": obj.get("sQuery"),
            "f_duration": obj.get("fDuration")
        })
        return _obj


