# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ComputedEEzsigndocumentSteptype(str, Enum):
    """
    Indicates whether the current step is a form or signatures.
    """

    """
    allowed enum values
    """
    FORM = 'Form'
    SIGN = 'Sign'
    NONE = 'None'

    @classmethod
    def from_json(cls, json_str: str) -> ComputedEEzsigndocumentSteptype:
        """Create an instance of ComputedEEzsigndocumentSteptype from a JSON string"""
        return ComputedEEzsigndocumentSteptype(json.loads(json_str))


