# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.3.1
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from eZmaxApi.models.custom_ezmaxcustomer_response import CustomEzmaxcustomerResponse
from eZmaxApi.models.email_response_compound import EmailResponseCompound
from eZmaxApi.models.phone_response_compound import PhoneResponseCompound
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomEzmaxcustomeruserResponse(BaseModel):
    """
    A Ezmaxcustomeruser Object
    """ # noqa: E501
    obj_ezmaxcustomer: CustomEzmaxcustomerResponse = Field(alias="objEzmaxcustomer")
    fki_contacttitle_id: Annotated[int, Field(strict=True, ge=0)] = Field(description="The unique ID of the Contacttitle.  Valid values:  |Value|Description| |-|-| |1|Ms.| |2|Mr.| |4|(Blank)| |5|Me (For Notaries)|", alias="fkiContacttitleID")
    fki_language_id: Annotated[int, Field(le=2, strict=True, ge=1)] = Field(description="The unique ID of the Language.  Valid values:  |Value|Description| |-|-| |1|French| |2|English|", alias="fkiLanguageID")
    obj_email: Optional[EmailResponseCompound] = Field(default=None, alias="objEmail")
    obj_phone: Optional[PhoneResponseCompound] = Field(default=None, alias="objPhone")
    s_ezmaxcustomeruser_firstname: Annotated[str, Field(strict=True)] = Field(description="The First name of the Ezmaxcustomeruser", alias="sEzmaxcustomeruserFirstname")
    s_ezmaxcustomeruser_lastname: Annotated[str, Field(strict=True)] = Field(description="The First name of the Ezmaxcustomeruser", alias="sEzmaxcustomeruserLastname")
    __properties: ClassVar[List[str]] = ["objEzmaxcustomer", "fkiContacttitleID", "fkiLanguageID", "objEmail", "objPhone", "sEzmaxcustomeruserFirstname", "sEzmaxcustomeruserLastname"]

    @field_validator('s_ezmaxcustomeruser_firstname')
    def s_ezmaxcustomeruser_firstname_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^.{1,20}$", value):
            raise ValueError(r"must validate the regular expression /^.{1,20}$/")
        return value

    @field_validator('s_ezmaxcustomeruser_lastname')
    def s_ezmaxcustomeruser_lastname_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^.{1,20}$", value):
            raise ValueError(r"must validate the regular expression /^.{1,20}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomEzmaxcustomeruserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of obj_ezmaxcustomer
        if self.obj_ezmaxcustomer:
            _dict['objEzmaxcustomer'] = self.obj_ezmaxcustomer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of obj_email
        if self.obj_email:
            _dict['objEmail'] = self.obj_email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of obj_phone
        if self.obj_phone:
            _dict['objPhone'] = self.obj_phone.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomEzmaxcustomeruserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "objEzmaxcustomer": CustomEzmaxcustomerResponse.from_dict(obj["objEzmaxcustomer"]) if obj.get("objEzmaxcustomer") is not None else None,
            "fkiContacttitleID": obj.get("fkiContacttitleID"),
            "fkiLanguageID": obj.get("fkiLanguageID"),
            "objEmail": EmailResponseCompound.from_dict(obj["objEmail"]) if obj.get("objEmail") is not None else None,
            "objPhone": PhoneResponseCompound.from_dict(obj["objPhone"]) if obj.get("objPhone") is not None else None,
            "sEzmaxcustomeruserFirstname": obj.get("sEzmaxcustomeruserFirstname"),
            "sEzmaxcustomeruserLastname": obj.get("sEzmaxcustomeruserLastname")
        })
        return _obj


