# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, conint, constr
from eZmaxApi.models.multilingual_ezmaxinvoicingsummaryinternal_description import MultilingualEzmaxinvoicingsummaryinternalDescription

class EzmaxinvoicingsummaryinternalResponse(BaseModel):
    """
    A Ezmaxinvoicingsummaryinternal Object  # noqa: E501
    """
    pki_ezmaxinvoicingsummaryinternal_id: Optional[conint(strict=True, ge=0)] = Field(None, alias="pkiEzmaxinvoicingsummaryinternalID", description="The unique ID of the Ezmaxinvoicingsummaryinternal")
    obj_ezmaxinvoicingsummaryinternal_description: MultilingualEzmaxinvoicingsummaryinternalDescription = Field(..., alias="objEzmaxinvoicingsummaryinternalDescription")
    s_ezmaxinvoicingsummaryinternal_description_x: constr(strict=True, max_length=70) = Field(..., alias="sEzmaxinvoicingsummaryinternalDescriptionX", description="The Ezmaxinvoicingsummaryinternal description in the language of the requester")
    fki_ezmaxinvoicing_id: Optional[conint(strict=True, ge=0)] = Field(None, alias="fkiEzmaxinvoicingID", description="The unique ID of the Ezmaxinvoicing")
    fki_billingentityinternal_id: conint(strict=True, ge=0) = Field(..., alias="fkiBillingentityinternalID", description="The unique ID of the Billingentityinternal.")
    s_billingentityinternal_description_x: StrictStr = Field(..., alias="sBillingentityinternalDescriptionX", description="The description of the Billingentityinternal in the language of the requester")
    __properties = ["pkiEzmaxinvoicingsummaryinternalID", "objEzmaxinvoicingsummaryinternalDescription", "sEzmaxinvoicingsummaryinternalDescriptionX", "fkiEzmaxinvoicingID", "fkiBillingentityinternalID", "sBillingentityinternalDescriptionX"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EzmaxinvoicingsummaryinternalResponse:
        """Create an instance of EzmaxinvoicingsummaryinternalResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of obj_ezmaxinvoicingsummaryinternal_description
        if self.obj_ezmaxinvoicingsummaryinternal_description:
            _dict['objEzmaxinvoicingsummaryinternalDescription'] = self.obj_ezmaxinvoicingsummaryinternal_description.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EzmaxinvoicingsummaryinternalResponse:
        """Create an instance of EzmaxinvoicingsummaryinternalResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EzmaxinvoicingsummaryinternalResponse.parse_obj(obj)

        _obj = EzmaxinvoicingsummaryinternalResponse.parse_obj({
            "pki_ezmaxinvoicingsummaryinternal_id": obj.get("pkiEzmaxinvoicingsummaryinternalID"),
            "obj_ezmaxinvoicingsummaryinternal_description": MultilingualEzmaxinvoicingsummaryinternalDescription.from_dict(obj.get("objEzmaxinvoicingsummaryinternalDescription")) if obj.get("objEzmaxinvoicingsummaryinternalDescription") is not None else None,
            "s_ezmaxinvoicingsummaryinternal_description_x": obj.get("sEzmaxinvoicingsummaryinternalDescriptionX"),
            "fki_ezmaxinvoicing_id": obj.get("fkiEzmaxinvoicingID"),
            "fki_billingentityinternal_id": obj.get("fkiBillingentityinternalID"),
            "s_billingentityinternal_description_x": obj.get("sBillingentityinternalDescriptionX")
        })
        return _obj


