# coding: utf-8

"""
    eZmax API Definition (Full)

    This API expose all the functionnalities for the eZmax and eZsign applications.

    The version of the OpenAPI document: 1.2.0
    Contact: support-api@ezmax.ca
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, constr, validator

class MultilingualSubnetDescription(BaseModel):
    """
    The description of the Subnet  # noqa: E501
    """
    s_subnet_description1: Optional[constr(strict=True)] = Field(None, alias="sSubnetDescription1", description="The description of the Subnet in French")
    s_subnet_description2: Optional[constr(strict=True)] = Field(None, alias="sSubnetDescription2", description="The description of the Subnet in English")
    __properties = ["sSubnetDescription1", "sSubnetDescription2"]

    @validator('s_subnet_description1')
    def s_subnet_description1_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^.{0,50}$", value):
            raise ValueError(r"must validate the regular expression /^.{0,50}$/")
        return value

    @validator('s_subnet_description2')
    def s_subnet_description2_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^.{0,50}$", value):
            raise ValueError(r"must validate the regular expression /^.{0,50}$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MultilingualSubnetDescription:
        """Create an instance of MultilingualSubnetDescription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MultilingualSubnetDescription:
        """Create an instance of MultilingualSubnetDescription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MultilingualSubnetDescription.parse_obj(obj)

        _obj = MultilingualSubnetDescription.parse_obj({
            "s_subnet_description1": obj.get("sSubnetDescription1"),
            "s_subnet_description2": obj.get("sSubnetDescription2")
        })
        return _obj


